/*
 * LanguageTool API
 *
 * Check texts for style and grammar issues with <a href='https://languagetool.org'>LanguageTool</a>. Please consider the following default limitations:<ul><li>your daily request limit depending on <a href='https://languagetool.org/editor/settings/access-tokens'>your plan</a> <li>maximum number of requests per minute: 20 (free) / 80 (Premium) <li>maximum number of characters per minute: 75,000 (free) / 300,000 (Premium) <li>maximum number of characters per request: 20,000 (free) / 60,000 (Premium) <li>for the free version, also consider the <a href='https://dev.languagetool.org/public-http-api'>limitations documented here</a> <li><b>Note:</b> any parameters or outputs not part of this documentation are internal and must not be relied on</ul> Need higher limits? See <a href='https://languagetool.org/proofreading-api'>Proofreading API plans</a>.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckPost200ResponseMatchesInnerReplacementsInner {
    /// the replacement string
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl CheckPost200ResponseMatchesInnerReplacementsInner {
    pub fn new() -> CheckPost200ResponseMatchesInnerReplacementsInner {
        CheckPost200ResponseMatchesInnerReplacementsInner { value: None }
    }
}
