/*
 * LanguageTool API
 *
 * Check texts for style and grammar issues with <a href='https://languagetool.org'>LanguageTool</a>. Please consider the following default limitations:<ul><li>your daily request limit depending on <a href='https://languagetool.org/editor/settings/access-tokens'>your plan</a> <li>maximum number of requests per minute: 20 (free) / 80 (Premium) <li>maximum number of characters per minute: 75,000 (free) / 300,000 (Premium) <li>maximum number of characters per request: 20,000 (free) / 60,000 (Premium) <li>for the free version, also consider the <a href='https://dev.languagetool.org/public-http-api'>limitations documented here</a> <li><b>Note:</b> any parameters or outputs not part of this documentation are internal and must not be relied on</ul> Need higher limits? See <a href='https://languagetool.org/proofreading-api'>Proofreading API plans</a>.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckPost200ResponseMatchesInnerRule {
    /// An rule's identifier that's unique for this language.
    #[serde(rename = "id")]
    pub id: String,
    /// An optional sub identifier of the rule, used when several rules are grouped.
    #[serde(rename = "subId", skip_serializing_if = "Option::is_none")]
    pub sub_id: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    /// An optional array of URLs with a more detailed description of the error.
    #[serde(rename = "urls", skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<models::CheckPost200ResponseMatchesInnerRuleUrlsInner>>,
    /// The <a href=\"http://www.w3.org/International/multilingualweb/lt/drafts/its20/its20.html#lqissue-typevalues\">Localization Quality Issue Type</a>. This is not defined for all languages, in which case it will always be 'Uncategorized'.
    #[serde(rename = "issueType", skip_serializing_if = "Option::is_none")]
    pub issue_type: Option<String>,
    #[serde(rename = "category")]
    pub category: Box<models::CheckPost200ResponseMatchesInnerRuleCategory>,
}

impl CheckPost200ResponseMatchesInnerRule {
    pub fn new(
        id: String,
        description: String,
        category: models::CheckPost200ResponseMatchesInnerRuleCategory,
    ) -> CheckPost200ResponseMatchesInnerRule {
        CheckPost200ResponseMatchesInnerRule {
            id,
            sub_id: None,
            description,
            urls: None,
            issue_type: None,
            category: Box::new(category),
        }
    }
}
