/*
 * LanguageTool API
 *
 * Check texts for style and grammar issues with <a href='https://languagetool.org'>LanguageTool</a>. Please consider the following default limitations:<ul><li>your daily request limit depending on <a href='https://languagetool.org/editor/settings/access-tokens'>your plan</a> <li>maximum number of requests per minute: 20 (free) / 80 (Premium) <li>maximum number of characters per minute: 75,000 (free) / 300,000 (Premium) <li>maximum number of characters per request: 20,000 (free) / 60,000 (Premium) <li>for the free version, also consider the <a href='https://dev.languagetool.org/public-http-api'>limitations documented here</a> <li><b>Note:</b> any parameters or outputs not part of this documentation are internal and must not be relied on</ul> Need higher limits? See <a href='https://languagetool.org/proofreading-api'>Proofreading API plans</a>.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckPost200ResponseMatchesInner {
    /// Message about the error displayed to the user.
    #[serde(rename = "message")]
    pub message: String,
    /// An optional shorter version of 'message'.
    #[serde(rename = "shortMessage", skip_serializing_if = "Option::is_none")]
    pub short_message: Option<String>,
    /// The 0-based character offset of the error in the text.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// The length of the error in characters.
    #[serde(rename = "length")]
    pub length: i32,
    /// Replacements that might correct the error. The array can be empty, in this case there is no suggested replacement.
    #[serde(rename = "replacements")]
    pub replacements: Vec<models::CheckPost200ResponseMatchesInnerReplacementsInner>,
    #[serde(rename = "context")]
    pub context: Box<models::CheckPost200ResponseMatchesInnerContext>,
    /// The sentence the error occurred in (since LanguageTool 4.0 or later)
    #[serde(rename = "sentence")]
    pub sentence: String,
    #[serde(rename = "rule", skip_serializing_if = "Option::is_none")]
    pub rule: Option<Box<models::CheckPost200ResponseMatchesInnerRule>>,
}

impl CheckPost200ResponseMatchesInner {
    pub fn new(
        message: String,
        offset: i32,
        length: i32,
        replacements: Vec<models::CheckPost200ResponseMatchesInnerReplacementsInner>,
        context: models::CheckPost200ResponseMatchesInnerContext,
        sentence: String,
    ) -> CheckPost200ResponseMatchesInner {
        CheckPost200ResponseMatchesInner {
            message,
            short_message: None,
            offset,
            length,
            replacements,
            context: Box::new(context),
            sentence,
            rule: None,
        }
    }
}
