/*
 * LanguageTool API
 *
 * Check texts for style and grammar issues with <a href='https://languagetool.org'>LanguageTool</a>. Please consider the following default limitations:<ul><li>your daily request limit depending on <a href='https://languagetool.org/editor/settings/access-tokens'>your plan</a> <li>maximum number of requests per minute: 20 (free) / 80 (Premium) <li>maximum number of characters per minute: 75,000 (free) / 300,000 (Premium) <li>maximum number of characters per request: 20,000 (free) / 60,000 (Premium) <li>for the free version, also consider the <a href='https://dev.languagetool.org/public-http-api'>limitations documented here</a> <li><b>Note:</b> any parameters or outputs not part of this documentation are internal and must not be relied on</ul> Need higher limits? See <a href='https://languagetool.org/proofreading-api'>Proofreading API plans</a>.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckPost200ResponseSoftware {
    /// Usually 'LanguageTool'.
    #[serde(rename = "name")]
    pub name: String,
    /// A version string like '3.3' or '3.4-SNAPSHOT'.
    #[serde(rename = "version")]
    pub version: String,
    /// Date when the software was built, e.g. '2016-05-25'.
    #[serde(rename = "buildDate")]
    pub build_date: String,
    /// Version of this API response. We don't expect to make incompatible changes, so this can also be increased for newly added fields.
    #[serde(rename = "apiVersion")]
    pub api_version: i32,
    /// An optional warning, e.g. when the API format is not stable.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// true if you're using a Premium account with all the premium text checks (since LanguageTool 4.2)
    #[serde(rename = "premium", skip_serializing_if = "Option::is_none")]
    pub premium: Option<bool>,
}

impl CheckPost200ResponseSoftware {
    pub fn new(
        name: String,
        version: String,
        build_date: String,
        api_version: i32,
    ) -> CheckPost200ResponseSoftware {
        CheckPost200ResponseSoftware {
            name,
            version,
            build_date,
            api_version,
            status: None,
            premium: None,
        }
    }
}
