name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      languagetool:
        image: erikvl87/languagetool:latest
        ports:
          - 8081:8010
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          cmd-format: nix develop -c {0}

      - name: Run CI checks
        run: nix develop -c cargo make ci
