/*
 * LanguageTool API
 *
 * Check texts for style and grammar issues with <a href='https://languagetool.org'>LanguageTool</a>. Please consider the following default limitations:<ul><li>your daily request limit depending on <a href='https://languagetool.org/editor/settings/access-tokens'>your plan</a> <li>maximum number of requests per minute: 20 (free) / 80 (Premium) <li>maximum number of characters per minute: 75,000 (free) / 300,000 (Premium) <li>maximum number of characters per request: 20,000 (free) / 60,000 (Premium) <li>for the free version, also consider the <a href='https://dev.languagetool.org/public-http-api'>limitations documented here</a> <li><b>Note:</b> any parameters or outputs not part of this documentation are internal and must not be relied on</ul> Need higher limits? See <a href='https://languagetool.org/proofreading-api'>Proofreading API plans</a>.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`check_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CheckPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`languages_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LanguagesGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`words_add_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WordsAddPostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`words_delete_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WordsDeletePostError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`words_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WordsGetError {
    UnknownValue(serde_json::Value),
}

/// The main feature - check a text with LanguageTool for possible style and grammar issues.
pub async fn check_post(
    configuration: &configuration::Configuration,
    language: &str,
    text: Option<&str>,
    data: Option<&str>,
    username: Option<&str>,
    api_key: Option<&str>,
    dicts: Option<&str>,
    mother_tongue: Option<&str>,
    preferred_variants: Option<&str>,
    enabled_rules: Option<&str>,
    disabled_rules: Option<&str>,
    enabled_categories: Option<&str>,
    disabled_categories: Option<&str>,
    enabled_only: Option<bool>,
    level: Option<&str>,
) -> Result<models::CheckPost200Response, Error<CheckPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_language = language;
    let p_form_text = text;
    let p_form_data = data;
    let p_form_username = username;
    let p_form_api_key = api_key;
    let p_form_dicts = dicts;
    let p_form_mother_tongue = mother_tongue;
    let p_form_preferred_variants = preferred_variants;
    let p_form_enabled_rules = enabled_rules;
    let p_form_disabled_rules = disabled_rules;
    let p_form_enabled_categories = enabled_categories;
    let p_form_disabled_categories = disabled_categories;
    let p_form_enabled_only = enabled_only;
    let p_form_level = level;

    let uri_str = format!("{}/check", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = p_form_text {
        multipart_form_params.insert("text", param_value.to_string());
    }
    if let Some(param_value) = p_form_data {
        multipart_form_params.insert("data", param_value.to_string());
    }
    multipart_form_params.insert("language", p_form_language.to_string());
    if let Some(param_value) = p_form_username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    if let Some(param_value) = p_form_api_key {
        multipart_form_params.insert("apiKey", param_value.to_string());
    }
    if let Some(param_value) = p_form_dicts {
        multipart_form_params.insert("dicts", param_value.to_string());
    }
    if let Some(param_value) = p_form_mother_tongue {
        multipart_form_params.insert("motherTongue", param_value.to_string());
    }
    if let Some(param_value) = p_form_preferred_variants {
        multipart_form_params.insert("preferredVariants", param_value.to_string());
    }
    if let Some(param_value) = p_form_enabled_rules {
        multipart_form_params.insert("enabledRules", param_value.to_string());
    }
    if let Some(param_value) = p_form_disabled_rules {
        multipart_form_params.insert("disabledRules", param_value.to_string());
    }
    if let Some(param_value) = p_form_enabled_categories {
        multipart_form_params.insert("enabledCategories", param_value.to_string());
    }
    if let Some(param_value) = p_form_disabled_categories {
        multipart_form_params.insert("disabledCategories", param_value.to_string());
    }
    if let Some(param_value) = p_form_enabled_only {
        multipart_form_params.insert("enabledOnly", param_value.to_string());
    }
    if let Some(param_value) = p_form_level {
        multipart_form_params.insert("level", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CheckPost200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CheckPost200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CheckPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn languages_get(
    configuration: &configuration::Configuration,
) -> Result<Vec<models::LanguagesGet200ResponseInner>, Error<LanguagesGetError>> {
    let uri_str = format!("{}/languages", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::LanguagesGet200ResponseInner&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::LanguagesGet200ResponseInner&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LanguagesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Add a word to one of the user's personal dictionaries. Please note that this feature is considered to be used for personal dictionaries which must not contain more than 500 words. If this is an issue for you, please contact us.
pub async fn words_add_post(
    configuration: &configuration::Configuration,
    word: &str,
    username: &str,
    api_key: &str,
    dict: Option<&str>,
) -> Result<models::WordsAddPost200Response, Error<WordsAddPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_word = word;
    let p_form_username = username;
    let p_form_api_key = api_key;
    let p_form_dict = dict;

    let uri_str = format!("{}/words/add", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("word", p_form_word.to_string());
    multipart_form_params.insert("username", p_form_username.to_string());
    multipart_form_params.insert("apiKey", p_form_api_key.to_string());
    if let Some(param_value) = p_form_dict {
        multipart_form_params.insert("dict", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WordsAddPost200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WordsAddPost200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WordsAddPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Remove a word from one of the user's personal dictionaries.
pub async fn words_delete_post(
    configuration: &configuration::Configuration,
    word: &str,
    username: &str,
    api_key: &str,
    dict: Option<&str>,
) -> Result<models::WordsDeletePost200Response, Error<WordsDeletePostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_word = word;
    let p_form_username = username;
    let p_form_api_key = api_key;
    let p_form_dict = dict;

    let uri_str = format!("{}/words/delete", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("word", p_form_word.to_string());
    multipart_form_params.insert("username", p_form_username.to_string());
    multipart_form_params.insert("apiKey", p_form_api_key.to_string());
    if let Some(param_value) = p_form_dict {
        multipart_form_params.insert("dict", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WordsDeletePost200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WordsDeletePost200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WordsDeletePostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// List words in the user's personal dictionaries.
pub async fn words_get(
    configuration: &configuration::Configuration,
    username: &str,
    api_key: &str,
    offset: Option<i32>,
    limit: Option<i32>,
    dicts: Option<&str>,
) -> Result<models::WordsGet200Response, Error<WordsGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_username = username;
    let p_query_api_key = api_key;
    let p_query_offset = offset;
    let p_query_limit = limit;
    let p_query_dicts = dicts;

    let uri_str = format!("{}/words", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("username", &p_query_username.to_string())]);
    req_builder = req_builder.query(&[("apiKey", &p_query_api_key.to_string())]);
    if let Some(ref param_value) = p_query_dicts {
        req_builder = req_builder.query(&[("dicts", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WordsGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WordsGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WordsGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
